---
#Usage: ansible-playbook 1_filters_for_variables.yml
- name: A simple playbook to illustrate processing variables using filters
  hosts: front
  become: false
  gather_facts: true # booleans to be lowercase if used in jinja
  tasks:
  - name: create a banner message
    copy: # multiline string
      content: | 
                Welcome to {{ ansible_hostname }}
                This is a production server,
                please do not make modifications unless needed! 
      dest: /etc/motd
    become: true
  - name: create folders  # looping a list
    file:
      path: "{{ front_home }}/{{ item }}"
      state: directory
      owner: root 
      group: root 
      mode: '0755'
    loop: "{{ folders }}"
    become: true
  - name: create a group
    group:
      name: frontgrp
      state: present 
    become: true
  - name: create many users # looping dictionary
    user:
      append: true
      name: "{{ item.name }}"
      create_home: true
      uid: "{{  ( item.uid | int | mandatory ) + 200 }}" # use mandatory filter
      home: "{{ item.home | default ( front_home + '/' + item.name , true ) }}" # use default filter with a variable
      comment: "{{ item.comment | default(omit) }}" # use default(omit) filter
      password: "{{ item.password | password_hash('sha512') }}" # use hash filter
      groups: frontgrp
    loop: "{{ users }}"
    become: true 
  - name: create archive directories 
    file:
      path: "{{ front_home }}/{{ 'archive_' + item }}"
      state: directory
      owner: root 
      group: root 
      mode: '0755'
    loop: "{{ folders }}"
    become: true
      
  - name: log created users
    copy:
      content: "Created users:  {{ users | json_query('[*].name') | join (', ') }}" # use json_query & join filters
      dest: "{{ front_home + '/logs/installation.log' }}" 
    become: true