---
#Usage: ansible-playbook 2_use_facts.yml -k ( to use in a job template, enable fact usage)
- name: Use fact cache
  hosts: all
  gather_facts: false
  order: sorted
  tasks:
  - name: display a fact using cache
    debug: 
      msg: "Total swap memory: {{ ansible_memory_mb | json_query('swap.total') }}"