---
# Usage: ansible-lint 3_apis.yml
- name: Simple playbook to test linting, kept on error ( line 14 ) for testing
  gather_facts: false
  become: false
  hosts: localhost
  vars:
    - tower_token: 'EUTwzeBQMFI26E0TQq9IY99HIWGzeO'
  tasks:
    - name: Login to a form based webpage
      uri:
        url: 'https://www.google.com/'
        method: GET
      register: login_details 
    - name: display list of users
      uri:
        url: "http://localhost/#/login"
        body_format: form-urlencoded
        body:
          cookie: csrftoken='riiaybRLQi5OJwaBZmSzfVaO7z7vPquKRtyTaDv7zIiXjeFhqYXH4bkab2NAWGgR'
          user: admin
          password: password
          enter: Log In
        method: POST
      register: users_details
